# Generated by Django 4.2.20 on 2025-03-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tips", models.TextField()),
                (
                    "light_needs",
                    models.CharField(
                        choices=[
                            ("Indirect light", "Indirect light"),
                            ("Low to medium", "Low to medium"),
                            ("Bright, indirect", "Bright, indirect"),
                            ("Low to bright", "Low to bright"),
                            ("Bright, direct", "Bright, direct"),
                            ("Filtered light", "Filtered light"),
                            ("Full sun", "Full sun"),
                            ("Full shade", "Full shade"),
                            ("Medium, indirect", "Medium, indirect"),
                            (
                                "Bright light with some direct sun",
                                "Bright light with some direct sun",
                            ),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "water_needs",
                    models.CharField(
                        choices=[
                            ("Very Low", "Very Low"),
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                            ("Very High", "Very High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "care",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Difficult", "Difficult"),
                        ],
                        max_length=10,
                    ),
                ),
                ("air_purifying", models.BooleanField(default=False)),
                ("allergenic", models.BooleanField(default=False)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Extra Small", "Extra Small"),
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                            ("Extra Large", "Extra Large"),
                        ],
                        max_length=15,
                    ),
                ),
                ("blooms", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Air-Purifying", "Air-Purifying"),
                            ("Decorative", "Decorative"),
                            ("Flowering", "Flowering"),
                            ("Succulent", "Succulent"),
                            ("Cactus", "Cactus"),
                            ("Rare", "Rare"),
                            ("Edible", "Edible"),
                            ("Medicinal", "Medicinal"),
                            ("Climbing", "Climbing"),
                            ("Ornamental Grass", "Ornamental Grass"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="verdespace.plant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plants/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="verdespace.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="comments/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="verdespace.comment",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="verdespace.plant",
                    ),
                ),
            ],
        ),
    ]
