# Generated by Django 4.2.20 on 2025-03-25 10:06

from django.db import migrations, models
import verdespace.models


class Migration(migrations.Migration):

    dependencies = [
        ("verdespace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to=verdespace.models.unique_image_name),
        ),
    ]
