# Generated by Django 4.2.20 on 2025-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verdespace", "0002_alter_plantimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
