# Generated by Django 4.2.20 on 2025-05-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verdespace", "0004_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="light_needs",
            field=models.CharField(
                choices=[
                    ("Bright", "Bright"),
                    ("Scattered", "Scattered"),
                    ("Shadow", "Shadow"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="water_needs",
            field=models.CharField(
                choices=[
                    ("Rarely", "Rarely"),
                    ("Moderately", "Moderately"),
                    ("Often", "Often"),
                ],
                max_length=15,
            ),
        ),
    ]
